[package]
name = "squalr"
version = "0.1.1"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
slint-mvvm = { path = "../slint-mvvm" }
slint-mvvm-macros = { path = "../slint-mvvm-macros" }
squalr-engine = { path = "../squalr-engine" }
squalr-engine-api = { path = "../squalr-engine-api" }
squalr-gui = { path = "../squalr-gui" }
log = ">=0.4.27"
slint = { version = ">=1.12.1", default-features = false, features = ["accessibility", "backend-winit", "compat-1-2", "renderer-software", "std"] }

[build-dependencies]
winresource = ">=0.1.20"
