[package]
name = "squalr-engine-domain"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"

[dependencies]
log = { version = "0.4.28" }
num-traits = { version = "0.2.19" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
