[package]
name = "slint-mvvm-macros"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = ">=2.0.95"
quote = ">=1.0.38"
proc-macro2 = ">=1.0.92"

[build-dependencies]

