[package]
name = "squalr-engine-architecture"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }

[build-dependencies]
